VacationManager/config/routes.rb
Rails.application.routes.draw do
  

  resources :vacations
  devise_for :users
  root 'pages#index'
  #root 'sessions#new'
  get 'about' => 'pages#about'
  get 'home' => 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

VacationManager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

VacationManager/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible no mass parameters allowed Rails 4+ onwards. Use gem 'strong_parameters'

  has_many :workers
  has_many :vacations
 
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
end

VacationManager/app/models/vacation.rb
class Vacation < ApplicationRecord
	validates_presence_of :worker_email
	validates_presence_of :start_date
	validates_presence_of :end_date
	
	validate :duration_of_vacation
	#validate :no_of_vacations

	def duration_of_vacation
		if ((end_date - start_date) > 30)
			errors.add(:vacation, "Should be less than 30 days")
			return
		end
	end	
end

VacationManager/app/models/worker.rb
class Worker < ApplicationRecord
	has_many :vacations
	belongs_to :user

end

VacationManager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
  	vacations_path
  end
end

VacationManager/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def home
  end

  def about
  end
end

VacationManager/app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)
    #Send an email (to the manager user_email) after the vacation is created
    @vacation.user_email=current_user.email
    VacationMailer.new_vacation(@vacation).deliver_now
    

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      params.require(:vacation).permit(:worker_email, :start_date, :end_date, :status)
    end

  end

VacationManager/app/helpers/application_helper.rb
module ApplicationHelper
end

VacationManager/app/helpers/pages_helper.rb
module PagesHelper
end

VacationManager/app/helpers/vacations_helper.rb
module VacationsHelper
end

VacationManager/app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  
   <%= link_to 'Vacation Manager', vacations_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
          <li><%= link_to 'Account  Settings' , edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out' , destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'About' , about_path%></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
      <% end %>
        <li class="dropdown">
          
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          
        </div>
        
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li></li>
        <li class="dropdown">
          
          
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

VacationManager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class = 'container'>
    <%= yield %>
    </div>
  </body>
</html>

VacationManager/app/views/pages/about.html.erb
<h3> Vacation management application</h3>
<h3> Rules </h3>
<h4> Manager Sign-up & log in to schedule the workers vacations upon request </h4>
<h4>Vacation has a start & end date</h4>
<h4> Vacations can't be more than 30 days per time</h4>
<h4> Vacations can't be more than 30 days in a year</h4>
<%= link_to 'Back', vacations_path %>

VacationManager/app/views/pages/home.html.erb
<div>

<h2>Welcome to the Vacation Manager</h2>
<h5>You can schedule and view workers vacations</h5>
<br><br>
<%= link_to 'Schedule Vacation', vacations_path, class: 'btn btn-primary btn-lg' %>

</div>

VacationManager/app/views/pages/index.html.erb
<div>

<h2>Welcome to the Vacation Manager</h2>
<h5>You can schedule and view workers vacations</h5>
<br><br>
<%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>

</div>

VacationManager/app/views/vacations/_form.html.erb
<%= simple_form_for(@vacation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :worker_email %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

VacationManager/app/views/vacations/edit.html.erb
<h1>Editing Vacation</h1>

<%= render 'form', vacation: @vacation %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

VacationManager/app/views/vacations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacations</h1>

<table>
  <thead>
    <tr>
      <th>Worker-email</th>
      <th>Start-date</th>
      <th>End-date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacations.each do |vacation| %>
      <tr>
        <td><%= vacation.worker_email %></td>
        <td><%= vacation.start_date %></td>
        <td><%= vacation.end_date %></td>
        <td><%= vacation.status %></td>
        <td><%= link_to 'Approve', vacation %></td>
        <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
        <td><%= link_to 'Reject', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation', new_vacation_path %>

VacationManager/app/views/vacations/new.html.erb
<h1>New Vacation</h1>

<%= render 'form', vacation: @vacation %>
	<% if @vacation.errors.any? %>
		<ul>
		<% @vacation.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>
<%= link_to 'Back', vacations_path %>

VacationManager/app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Worker-email:</strong>
  <%= @vacation.worker_email %>
</p>

<p>
  <strong>Start-date:</strong>
  <%= @vacation.start_date %>
</p>

<p>
  <strong>End-date:</strong>
  <%= @vacation.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @vacation.status %>
</p>

<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>